### ISSUE TITLE
examples/rethinkdb_sync.py not work

### ISSUE THREAD

**Issue by amartinelli** [noplay/python-mysql-replication#128]
./rethinkdb_sync.py 
Traceback (most recent call last):
  File "./rethinkdb_sync.py", line 65, in <module>
    main()
  File "./rethinkdb_sync.py", line 36, in main
    rethinkdb.db_create("mysql").run()
  File "/usr/lib/python2.6/site-packages/rethinkdb/ast.py", line 116, in run
    " a connection to run on.")
rethinkdb.errors.ReqlDriverError: RqlQuery.run must be given a connection to run on.

Anybody help-me ?

**Comment by amartinelli** [comment]
#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Insert a new element in  a RethinkDB database
# when an evenement is trigger in MySQL replication log
#
# Please test with MySQL employees DB available here:
# https://launchpad.net/test-db/
#

import rethinkdb as rdb

from pymysqlreplication import BinLogStreamReader
from pymysqlreplication.row_event import (
    DeleteRowsEvent,
    UpdateRowsEvent,
    WriteRowsEvent,
)

MYSQL_SETTINGS = {
    "host": "192.168.0.10",
    "port": 3306,
    "user": "root",
    "passwd": "password"
}


def main():
    # connect rethinkdb
    
    rdb.connect("localhost", 28015, "mysql").repl()
    try:
        rdb.db_drop("mysql").run()
    except:
        pass
    rdb.db_create("mysql").run()

    tables = ["Experts"]
    for table in tables:
        rdb.db("mysql").table_create(table).run()

   stream = BinLogStreamReader(
        connection_settings=MYSQL_SETTINGS,
        server_id=1,
        resume_stream=False,
        blocking=True,
        only_events=[DeleteRowsEvent, WriteRowsEvent, UpdateRowsEvent],
    )

    # process Feed
    for binlogevent in stream:
        if not isinstance(binlogevent, WriteRowsEvent):
            continue

        for row in binlogevent.rows:
            if not binlogevent.schema == "GAQhomologa":
                continue

            vals = dict((str(k), str(v)) for k, v in row["values"].iteritems())
            rdb.table(binlogevent.table).insert(vals).run()

    stream.close()


if __name__ == "__main__":
    main()
