### ISSUE TITLE
UTF-8 error on rethinkdb_sync.py 

### ISSUE THREAD

**Issue by amartinelli** [noplay/python-mysql-replication#130]
Hi ,

I try to do work the rethinkdb_sync example file but shoiw me error:

Traceback (most recent call last):
  File "./rethinkdb_sync.py", line 67, in <module>
    main()
  File "./rethinkdb_sync.py", line 60, in main
    vals = dict((str(k), str(v)) for k, v in row["values"].iteritems())
  File "./rethinkdb_sync.py", line 60, in <genexpr>
    vals = dict((str(k), str(v)) for k, v in row["values"].iteritems())

Where i do encode or decode utf-8 ?

**Comment by noplay** [comment]
The example is not supported. Sorry I have removed it from the examples directory.
