### ISSUE TITLE
Decoding binary as utf-8

### ISSUE THREAD

**Issue by MartinAmps** [noplay/python-mysql-replication#132]
I get this trace:

Traceback (most recent call last):
  File "./test.py", line 33, in <module>
    main()
  File "./test.py", line 26, in main
    for binlogevent in stream:
  File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/binlogstream.py", line 262, in fetchone
    self.__freeze_schema)
  File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/packet.py", line 98, in __init__
    freeze_schema = freeze_schema)
  File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/event.py", line 141, in __init__
    self.query = tmp.decode("utf-8")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xae in position 460: invalid start byte

I printed a repr of the packet and it is essentially:

    INSERT INTO x(......, ip) VALUES (....,  'b\xae\xe1\xbd');

This is row based replication where the master was originally sent INET6_ATON('::1') for example.

What's the recommended solution here? I'm surprised no one else has hit this as many column types leverage binary.

Thanks!

**Comment by noplay** [comment]
Can you post the type of the column?

Le jeu. 17 sept. 2015 à 00:56, Martin Amps <notifications@github.com> a
écrit :

**Comment by MartinAmps** [comment]
Apologies - it’s a varbinary(15)

**Comment by noplay** [comment]
No problem :) Thanks a lot for the report. Sorry if I was rude in my
question I just wake up :P

Le jeu. 17 sept. 2015 à 08:15, Martin Amps <notifications@github.com> a
écrit :

> Apologies - it’s a varbinary(15)
>
> > On Sep 16, 2015, at 11:13 PM, Julien Duponchelle <

**Comment by MartinAmps** [comment]
No problem at all. Let me know if I can help at all debugging further - right now I just wrapped it in a try: except: block to make it fail a bit more gracefully, was planning to dive in a little deeper tomorrow. Bed time here on the west coast!

**Comment by noplay** [comment]
I think we can ignore the invalid unicode char (do not break existing app) or return a byte string

**Comment by MartinAmps** [comment]
I agree, it would probably be useful to parse it out in future but for now the potential exceptions should be fixed
