### ISSUE TITLE
got error with running dump_events.py 

### ISSUE THREAD

**Issue by liujian883** [noplay/python-mysql-replication#152]
Hi,
I run the dump_events.py with ubuntu 14.04(mysql 5.5.47),and I got this error:

ehigh@home:~/tmp/python-mysql-replication/examples$ python dump_events.py 
Traceback (most recent call last):
  File "dump_events.py", line 33, in <module>
    main()
  File "dump_events.py", line 26, in main
    for binlogevent in stream:
  File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/binlogstream.py", line 243, in fetchone
    pkt = self._stream_connection._read_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 953, in _read_packet
    (packet_number, self._next_seq_id))
pymysql.err.InternalError: Packet sequence number wrong - got 1 expected 9

How can I solve this problem?
Thanks a lot!!!

**Comment by porschelau** [comment]
Check you pymysql version

**Comment by baloo** [comment]
I believe this has been fixed in 0.9 version of python-mysql-replication therefore I close this issue, feel free to reopen.
