### ISSUE TITLE
pymysql.err.InternalError: (1236, u'Could not find first log file name in binary log index file')

### ISSUE THREAD

**Issue by yuanminxue** [noplay/python-mysql-replication#154]
from pymysqlreplication import BinLogStreamReader

MYSQL_SETTINGS = {
    "host": "127.0.0.1",
    "port": 3306,
    "user": "root",
    "passwd": ""
}
def main():
    stream = BinLogStreamReader(connection_settings=MYSQL_SETTINGS,
        server_id=610,
        log_file="/u02/mysql/mysql-bin.000012",
        log_pos=23569311)
    for binlog_event in stream:
        binlog_event.dump()
    stream.close()

if __name__ == "__main__":
    main()
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "mysql_binlog_dump.py", line 28, in <module>
    main()
  File "mysql_binlog_dump.py", line 23, in main
    for binlog_event in stream:
  File "/usr/lib/python2.6/site-packages/pymysqlreplication/binlogstream.py", line 243, in fetchone
    pkt = self._stream_connection._read_packet()
  File "/usr/lib64/python2.6/site-packages/pymysql/connections.py", line 826, in _read_packet
    packet.check_error()
  File "/usr/lib64/python2.6/site-packages/pymysql/connections.py", line 373, in check_error
    raise_mysql_exception(self.__data)
  File "/usr/lib64/python2.6/site-packages/pymysql/err.py", line 117, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/lib64/python2.6/site-packages/pymysql/err.py", line 113, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
pymysql.err.InternalError: (1236, u'Could not find first log file name in binary log index file')

can u help me?

**Comment by yuanminxue** [comment]
can i dump binlog data by  use log_file and log_pos  way?

**Comment by baloo** [comment]
I'm not sure to get your question, but the error in the your first message comes directly from your mysql server and basically says your server doesn't have the specified logfile. I think a full path is unexpected here and you should only put filename (by the `basename(1)` meaning) and let mysqld figure it out by itself.

I'm not sure to get this question:
> can i dump binlog data by use log_file and log_pos way?
