### ISSUE TITLE
How to make the stream restart from it last stop?

### ISSUE THREAD

**Issue by jiamo** [noplay/python-mysql-replication#217]
When using `resume_stream=True` . After my program stop. I changed a mysql a row. But when I a restart my program. There is no event in stream.

In doc:
```
       log_file: Set replication start log file
       log_pos: Set replication start log pos (resume_stream should be true)
```
But the mysql bin log file always changes. when eavl `show master status`
```
mysql> show master status;
+----------------------------+----------+--------------+------------------+-------------------+
| File                       | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+----------------------------+----------+--------------+------------------+-------------------+
| mysql-bin-changelog.018311 |     5117 |              |                  |                   |
+----------------------------+----------+--------------+------------------+-------------------+

```

So  how can I achieve this. After I restart my program. The change of mysql can be in the stream?

**Comment by noplay** [comment]
The lib doesn't keep the position you need to keep the position and pass it.

**Comment by jiamo** [comment]
Thanks.  How about  log file name like  `mysql-bin-changelog.018357`. It always changed.
When my program is running, what happened the mysql bin-log file changed?

**Comment by bjoernhaeuser** [comment]
The application receives a rotate event, which tells you the new file name. The position inside is included in every event. 

Björn

**Comment by jiamo** [comment]
Thanks.  I have look into the source.
In `BinLogStreamReader:fetch`

```
            if binlog_event.event_type == ROTATE_EVENT:
                self.log_pos = binlog_event.event.position
                self.log_file = binlog_event.event.next_binlog
```
seem already keep the log file. So I try to remeber it at exit.

```
def goodbye(stream, cache):
    print("I got goodbye")
    cache.set(BINLOG_FILE_NAME_KEY, stream.log_file)
    cache.set(BINLOG_FILE_POS_KEY, stream.log_pos)


def main():


    cache = redis.StrictRedis(host=user_config["REDIS_URL"], port=6379, db=0)
    old_log_file = cache.get(BINLOG_FILE_NAME_KEY)
    old_log_pos = cache.get(BINLOG_FILE_POS_KEY)
    old_log_file = str(old_log_file, encoding="utf-8") if old_log_file else None
    old_log_pos = int(old_log_pos) if old_log_pos else None

    stream = BinLogStreamReader(
        connection_settings=mysql_setting,
        server_id=int(user_config["MYSQL_SERVER_ID"]),
        blocking=True,
        resume_stream=True,
        only_events=[DeleteRowsEvent, WriteRowsEvent, UpdateRowsEvent],
        log_file=old_log_file,
        log_pos=old_log_pos
    )
    # for only slave don't need
    # stream.report_slave = report_slave
    atexit.register(goodbye, stream=stream, cache=cache)
```

After some running. I am confused:

In One case.

```
I got goodbye
'end at mysql-bin-changelog.018574 2222259'

```
I stop my program and do many flush.


```
mysql> show master status;
+----------------------------+----------+--------------+------------------+-------------------+
| File                       | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+----------------------------+----------+--------------+------------------+-------------------+
| mysql-bin-changelog.018574 |  3264625 |              |                  |                   |
+----------------------------+----------+--------------+------------------+-------------------+
1 row in set (0.00 sec)

mysql> show master status;
+----------------------------+----------+--------------+------------------+-------------------+
| File                       | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+----------------------------+----------+--------------+------------------+-------------------+
| mysql-bin-changelog.018575 |      120 |              |                  |                   |
+----------------------------+----------+--------------+------------------+-------------------+

```

The master binlog file have changed.
Then I start my program:

```
begin at mysql-bin-changelog.018574 2222259
2 UpdateRowsEvent
2 UpdateRowsEvent
^CTraceback (most recent call last):
  File "main.py", line 95, in <module>
    main()
  File "main.py", line 82, in main
    for binlogevent in stream:
  File "/home/ubuntu/.pyenv/versions/aflt_proxy/lib/python3.5/site-packages/pymysqlreplication/binlogstream.py", line 408, in fetchone
    pkt = self._stream_connection._read_packet()
  File "/home/ubuntu/.pyenv/versions/aflt_proxy/lib/python3.5/site-packages/pymysql/connections.py", line 983, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/ubuntu/.pyenv/versions/aflt_proxy/lib/python3.5/site-packages/pymysql/connections.py", line 1017, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "/home/ubuntu/.pyenv/versions/3.5.2/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
I got goodbye
'end at mysql-bin-changelog.018575 120'

```

I don't finish fetch and input `ctrl-c`. But this time the `stream file` already be the latest  `log_file` and `log_pos`  which is not my want.  It should still be  `mysql-bin-changelog.018574` and some pos big than `2222259`

Any suggestion?

**Comment by bjoernhaeuser** [comment]
Looks correct to me. For more debugging set the only_events to None and print all positions you receive.

**Comment by jiamo** [comment]
Thanks. I try debug today. But the every begging . it show

```
begin at mysql-bin-changelog.018575 120
Traceback (most recent call last):
  File "main.py", line 95, in <module>
    main()
  File "main.py", line 82, in main
    for binlogevent in stream:
  File "/home/ubuntu/.pyenv/versions/aflt_proxy/lib/python3.5/site-packages/pymysqlreplication/binlogstream.py", line 408, in fetchone
    pkt = self._stream_connection._read_packet()
  File "/home/ubuntu/.pyenv/versions/aflt_proxy/lib/python3.5/site-packages/pymysql/connections.py", line 1010, in _read_packet
    packet.check_error()
  File "/home/ubuntu/.pyenv/versions/aflt_proxy/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/.pyenv/versions/aflt_proxy/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1236, 'Could not find first log file name in binary log index file')
I got goodbye
'end at mysql-bin-changelog.018575 120'

```
It seem that what I save the binlog file can't be used any more. and master status already

```
 show master status;
+----------------------------+----------+--------------+------------------+-------------------+
| File                       | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+----------------------------+----------+--------------+------------------+-------------------+
| mysql-bin-changelog.018814 |      410 |              |                  |                   |
+----------------------------+----------+--------------+------------------+-------------------+

```

So If I can't save log_file using this method and the log_pos is useless .
In this case I can't read the history binlog stream any more?

**Comment by jiamo** [comment]
I find the reason. The aws rds don't keep much binlog file if you don't change the `binlog retention hours`

**Comment by gonzalodiaz** [comment]
@jiamo how did you fix this issue?

Have you set a `binlog retention hours` value that worked for you? In that case, what was the value?

Or did you handle it differently in the code?
