### ISSUE TITLE
Unable to parse DATE from data. 

### ISSUE THREAD

**Issue by mva1991** [noplay/python-mysql-replication#276]
Hello,
I just installed this repo in my development instance - Planning to stream binlogs to logstash.
I am running into this issue - When I try the first step of executing the python program. 
I really appreciate all the help.

```
[root@NODE1 logstash]# python mysql_to_logstash.py
Traceback (most recent call last):
  File "mysql_to_logstash.py", line 55, in <module>
    main()
  File "mysql_to_logstash.py", line 47, in main
    print json.dumps(event)
  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2018, 8, 14, 14, 0) is not JSON serializable
```

**Comment by baloo** [comment]
this error has nothing to do with python-mysql-replication, have you tried googling your error before opening an issue? http://lmgtfy.com/?q=datetime.datetime+is+not+JSON+serializable
